[project]
name = "ephys-link"
version = "5.1.0.dev1"
description = "Electrophysiology manipulator communication platform."
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]

[tool.ruff]
fix = true

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
preset = "strict"


[dependency-groups]
dev = [
    "lefthook>=2.1.11",
    "pyrefly>=1.2.0",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-mock>=3.15.1",
    "ruff>=0.16.4",
]
