name: Code Quality

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: 📦 Install ruff
        uses: astral-sh/ruff-action@278981a28ce3188b1e39527901f38254bf3aac89

      - name: 📝 Format Code
        run: ruff format --check

      - name: 🔍 Lint Code
        run: ruff check

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: 🛎 Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1

      - name: 🔭 Install UV
        uses: astral-sh/setup-uv@20cfd1bf945f4377ade1205e4dbc17946fc9a30d
        with:
          activate-environment: 'true'

      - name: 🔄 Sync Dependencies
        run: uv sync

      - name: 🔍 Type Check
        run: pyrefly check --output-format=github
